name: MPVClaim
version: 1.0
api-version: 1.19
authors: [GeekLegend, Kenda_]
main: com.geeklegend.MPVClaim
depend:
  - Vault
  - ProtocolLib
  - LuckPerms
  - DecentHolograms
commands:
  mpv:
    usage: /mpv